version: "2"
run:
  tests: true
linters:
  enable:
    - gocritic
    - revive
  settings:
    revive:
      severity: warning
      rules:
        - name: var-naming
        - name: exported
        - name: package-comments
        - name: unused-parameter
        - name: indent-error-flow
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 3
formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
