name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
      - name: Go mod tidy (no diff)
        run: go mod tidy && git diff --exit-code
      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --timeout=5m
      - name: Test (race + cover)
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
      - name: Govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ matrix.go-version }}
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out
