name: Release Drafter
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, synchronize, closed]
permissions:
  contents: read
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}